import Head from 'next/head'
import HomeComp from '../components/Home'
import Pagination from '../components/Pagination'
import { useRouter } from 'next/router'
import { ChangeEvent, useState, useEffect } from 'react'
import { PokemonDataProps } from '../types'
import { getPokemons } from '../utils'

const Page = () => {
  const router = useRouter()
  const { page } = router.query
  const [selectedOption, setSelectedOption] = useState<number>(10)
  const [pokemonData, setPokemonData] = useState<PokemonDataProps[]>([])
  const [pageCount, setPageCount] = useState<number>(1)
  const handleSelectedOption = (e: ChangeEvent<HTMLSelectElement>) =>
    setSelectedOption(Number(e.target.value))

  useEffect(() => {
    const getData = async () => {
      const res = await getPokemons(selectedOption, Number(page))
      setPokemonData(res)
    }
    getData()

    setPageCount(Math.ceil(900 / selectedOption))
  }, [selectedOption, page])

  // console.log(pageCount)

  if (!pokemonData) return <p>Loading...</p>
  if (page === '0') router.replace('/')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-slate-200">
        <HomeComp
          pokemonData={pokemonData}
          selectedValue={selectedOption}
          handleSelectChange={handleSelectedOption}
        />
        <Pagination total={pageCount} />
      </div>
    </>
  )
}

export default Page
