import type { GetStaticProps } from 'next'
import Head from 'next/head'

import HomeComp from '../components/Home'
import { HomepageProps, PokemonDataProps } from '../types'

const Home = ({ pokemonData }: HomepageProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-slate-200">
        <HomeComp pokemonData={pokemonData} />
      </div>
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const urlArr = []
  for (let i = 0; i < 20; i++) {
    urlArr.push(`${process.env.POKEMON_LIST}/${i + 1}`)
  }

  const requests = urlArr.map((url) => fetch(url))
  const responses = await Promise.all(requests)
  const promises = responses.map((res) => res.json())
  const finalRes = await Promise.all(promises)
  // console.log(finalRes)
  const pokemonArr: PokemonDataProps[] = []
  finalRes.map((pokemon) => {
    const temp = {
      name: pokemon.name,
      abilities: pokemon.abilities || null,
      baseExp: pokemon.base_experience || null,
      height: pokemon.height || null,
      avatar: pokemon.sprites.other.dream_world.front_default || null,
      stats: pokemon.stats || null,
      types: pokemon.types || null,
      weight: pokemon.weight || null,
    }
    pokemonArr.push(temp)
  })

  return {
    props: {
      pokemonData: pokemonArr,
    },
  }
}

export default Home
